# Generated by Django 4.2.3 on 2024-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('fincode', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('file_section', models.FileField(blank=True, null=True, upload_to='user_files/')),
            ],
        ),
    ]
