# Generated by Django 4.2.3 on 2024-03-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='file_section',
            new_name='attachment',
        ),
    ]
