# Generated by Django 4.2.3 on 2024-03-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_file_section_userprofile_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(default=datetime.datetime(2024, 3, 6, 12, 27, 36, 978099, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='register_type',
            field=models.CharField(default=datetime.datetime(2024, 3, 6, 12, 27, 42, 859209, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
